server:
    port: 8081

logging:
  level:
    org.springframework.web: INFO
    com.adidas.itinerarycalculator: DEBUG

spring:
  application:
      name: "ItineraryCalculator"

feign:
  hystrix:
    enabled: true
  itineraryManager:
    name: "ItineraryManager"
    url: "http://it-manager:8080"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
  instance:
    preferIpAddress: true
    hostname: eureka-server
    port: 8761